# Generated by Django 4.0.2 on 2022-05-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
