# Generated by Django 4.0.2 on 2022-05-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
