# Generated by Django 4.0.2 on 2022-08-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
