# Generated by Django 4.0.2 on 2022-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachunek',
            name='kategoria',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rachunek',
            name='kwota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
