# Generated by Django 4.0.2 on 2022-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0007_alter_rachunek_kategoria_alter_rachunek_kwota'),
    ]

    operations = [
        migrations.AddField(
            model_name='rachunek',
            name='domyslne',
            field=models.BooleanField(default=False),
        ),
    ]
