# Generated by Django 4.0.2 on 2022-11-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0008_rachunek_domyslne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rachunek',
            name='domyslne',
        ),
    ]
