# Generated by Django 4.0.2 on 2022-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0009_remove_rachunek_domyslne'),
    ]

    operations = [
        migrations.AddField(
            model_name='rachunek',
            name='domyslne',
            field=models.BooleanField(default=False),
        ),
    ]
