# Generated by Django 4.0.2 on 2022-11-12 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanse', '0013_kategoria_user_delete_kategoriauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dluznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('kwota_do_splaty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('splacony', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kategoria',
            unique_together={('user', 'nazwa')},
        ),
        migrations.CreateModel(
            name='DluznikSplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_splaty', models.DateTimeField(auto_now_add=True)),
                ('dluznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanse.dluznik')),
            ],
        ),
    ]
