# Generated by Django 4.0.2 on 2022-11-22 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanse', '0014_dluznik_alter_kategoria_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_dluznika', models.CharField(max_length=200)),
                ('kwota_do_splaty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('splacony', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DlugSplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_splaty', models.DateTimeField(auto_now_add=True)),
                ('dlug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanse.dlug')),
            ],
        ),
        migrations.RemoveField(
            model_name='dluzniksplata',
            name='dluznik',
        ),
        migrations.DeleteModel(
            name='Dluznik',
        ),
        migrations.DeleteModel(
            name='DluznikSplata',
        ),
    ]
