# Generated by Django 4.0.2 on 2022-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0015_dlug_dlugsplata_remove_dluzniksplata_dluznik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlug',
            name='cel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
