# Generated by Django 4.0.2 on 2022-11-22 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanse', '0016_dlug_cel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlugsplata',
            name='rachunek',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finanse.rachunek'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dlugsplata',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dlugsplata',
            name='kwota',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
