# Generated by Django 4.0.2 on 2022-11-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0018_remove_dlugsplata_rachunek'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlug',
            name='rachunek',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finanse.rachunek'),
            preserve_default=False,
        ),
    ]
