# Generated by Django 4.0.2 on 2022-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0019_dlug_rachunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlugsplata',
            name='data_splaty',
            field=models.DateField(),
        ),
    ]
