# Generated by Django 4.0.2 on 2022-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0020_alter_dlugsplata_data_splaty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlug',
            name='cel',
            field=models.CharField(default='', max_length=200),
        ),
    ]
