# Generated by Django 4.0.2 on 2022-12-14 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='przychod',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('przychod', models.BooleanField(default=False)),
                ('opis', models.CharField(blank=True, max_length=500)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.kategoria')),
                ('rachunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.rachunek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
